# Generated by Django 3.1 on 2020-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
