# Generated by Django 3.1 on 2020-09-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_blogmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='user',
        ),
    ]
