# Generated by Django 3.1 on 2020-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_logomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomodel',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
