# Generated by Django 3.1 on 2020-09-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20200906_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogoModel',
            new_name='LogoImage',
        ),
    ]
