# Generated by Django 3.1 on 2020-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_auto_20200906_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoImage',
        ),
    ]
